.\MasNetworkDataParser\MasNetworkDataParser\bin\Release\MasNetworkDataParser.exe "E:\MAS\RUN_2\baseline\NonAggregateNetworkData.2015.Apr.30.14_36_47.csv"
.\MasNetworkDataParser\MasNetworkDataParser\bin\Release\MasNetworkDataParser.exe "E:\MAS\RUN_2\churn_high\NonAggregateNetworkData.2015.Apr.30.14_39_00.csv"
.\MasNetworkDataParser\MasNetworkDataParser\bin\Release\MasNetworkDataParser.exe "E:\MAS\RUN_2\churn_low\NonAggregateNetworkData.2015.Apr.30.14_42_15.csv"
.\MasNetworkDataParser\MasNetworkDataParser\bin\Release\MasNetworkDataParser.exe "E:\MAS\RUN_2\connection_high\NonAggregateNetworkData.2015.Apr.30.14_44_53.csv"
.\MasNetworkDataParser\MasNetworkDataParser\bin\Release\MasNetworkDataParser.exe "E:\MAS\RUN_2\connection_low\NonAggregateNetworkData.2015.Apr.30.14_46_48.csv"
.\MasNetworkDataParser\MasNetworkDataParser\bin\Release\MasNetworkDataParser.exe "E:\MAS\RUN_2\leaf_and_ultra\NonAggregateNetworkData.2015.Apr.30.14_50_17.csv"
.\MasNetworkDataParser\MasNetworkDataParser\bin\Release\MasNetworkDataParser.exe "E:\MAS\RUN_2\ping_high\NonAggregateNetworkData.2015.Apr.30.14_53_17.csv"
.\MasNetworkDataParser\MasNetworkDataParser\bin\Release\MasNetworkDataParser.exe "E:\MAS\RUN_2\ping_low\NonAggregateNetworkData.2015.Apr.30.14_57_46.csv"